/**
 * Eco-Nudge Negotiator - Environmental & Nutritional Data Module
 * 
 * Contains carbon footprint data (kg CO2e per kg of food),
 * nutritional information, and sustainable substitution mappings.
 * 
 * Data sources:
 * - Poore & Nemecek (2018), Science: "Reducing food's environmental impacts"
 * - Our World in Data: Environmental impacts of food production
 * - USDA FoodData Central for nutritional values
 */

const EcoData = (() => {

    // Carbon footprint in kg CO2e per kg of food product
    const carbonFootprint = {
        // Meats (high impact)
        'beef': 27.0,
        'lamb': 24.0,
        'pork': 7.6,
        'chicken': 6.9,
        'turkey': 5.5,
        'bacon': 8.0,
        'sausage': 7.0,
        'salami': 8.5,
        'ham': 7.2,

        // Seafood
        'shrimp': 11.8,
        'prawns': 11.8,
        'salmon': 5.4,
        'tuna': 6.1,
        'cod': 3.5,
        'fish': 4.0,

        // Dairy (moderate-high)
        'cheese': 13.5,
        'butter': 11.9,
        'cream': 7.6,
        'milk': 3.2,
        'yogurt': 2.5,
        'eggs': 4.8,
        'ice cream': 6.0,

        // Plant proteins (low impact)
        'tofu': 2.0,
        'tempeh': 1.8,
        'lentils': 0.9,
        'chickpeas': 0.8,
        'beans': 0.7,
        'black beans': 0.7,
        'kidney beans': 0.7,
        'peas': 0.8,
        'peanuts': 1.3,
        'almonds': 2.3,
        'walnuts': 2.2,
        'cashews': 2.5,
        'seitan': 1.5,

        // Grains
        'rice': 2.7,
        'pasta': 1.8,
        'bread': 1.6,
        'wheat': 1.4,
        'oats': 1.6,
        'quinoa': 1.2,
        'couscous': 1.3,
        'flour': 1.4,

        // Vegetables (very low)
        'potatoes': 0.5,
        'tomatoes': 1.4,
        'onions': 0.4,
        'carrots': 0.4,
        'broccoli': 0.8,
        'spinach': 0.5,
        'lettuce': 0.7,
        'peppers': 1.0,
        'mushrooms': 0.6,
        'zucchini': 0.5,
        'eggplant': 0.6,
        'cabbage': 0.4,
        'cauliflower': 0.7,
        'kale': 0.5,
        'sweet potato': 0.5,
        'corn': 0.7,
        'avocado': 1.3,
        'cucumber': 0.4,
        'celery': 0.3,
        'garlic': 0.5,
        'ginger': 0.6,

        // Fruits
        'banana': 0.7,
        'apple': 0.4,
        'orange': 0.5,
        'berries': 1.1,
        'strawberries': 1.1,
        'grapes': 0.8,
        'mango': 1.0,
        'pineapple': 0.9,
        'lemon': 0.3,
        'lime': 0.3,
        'coconut': 1.0,

        // Oils & Condiments
        'olive oil': 3.5,
        'vegetable oil': 2.8,
        'coconut oil': 3.2,
        'soy sauce': 1.0,
        'sugar': 1.8,
        'honey': 1.2,
        'maple syrup': 1.1,
        'chocolate': 4.5,
        'cocoa': 4.5,

        // Beverages
        'coffee': 8.0,
        'tea': 1.2,

        // Plant milks & creams
        'oat milk': 0.9,
        'soy milk': 1.0,
        'almond milk': 0.7,
        'coconut milk': 1.2,
        'coconut cream': 1.5,
        'cashew cream': 1.2,
        'oat cream': 0.9,

        // Plant-based alternatives
        'jackfruit': 0.8,
        'hearts of palm': 0.7,
        'banana blossom': 0.5,
        'king oyster mushrooms': 0.7,
        'cauliflower rice': 0.7,
        'bulgur': 1.2,
        'nutritional yeast': 1.5,
        'hummus': 1.0,
        'tahini': 1.6,
        'smoked tempeh': 1.9,
        'smoked tofu': 2.1,
        'silken tofu': 2.0,
        'marinated tofu': 2.1,
        'tofu scramble': 2.0,
        'coconut bacon': 1.3,
        'carob': 1.5,
        'chicory root': 0.4,
        'cocoa nibs': 3.5,
        'coconut yogurt': 1.2,
        'soy yogurt': 1.0,
        'oat yogurt': 0.9,
        'chickpea flour': 0.9,
        'chickpea pasta': 1.1,
        'lentil pasta': 1.0,
        'zucchini noodles': 0.5,
        'flax eggs': 0.5,
        'chia eggs': 0.6,
        'banana ice cream': 0.8,
        'coconut ice cream': 1.5,
        'white beans': 0.7,
    };

    // Nutritional data per 100g (simplified)
    const nutritionData = {
        'beef': { calories: 250, protein: 26, fiber: 0, iron: 2.6, vitaminC: 0, category: 'protein' },
        'chicken': { calories: 165, protein: 31, fiber: 0, iron: 1.0, vitaminC: 0, category: 'protein' },
        'pork': { calories: 242, protein: 27, fiber: 0, iron: 1.0, vitaminC: 0, category: 'protein' },
        'lamb': { calories: 294, protein: 25, fiber: 0, iron: 1.9, vitaminC: 0, category: 'protein' },
        'salmon': { calories: 208, protein: 20, fiber: 0, iron: 0.8, vitaminC: 0, category: 'protein' },
        'tofu': { calories: 144, protein: 15, fiber: 0.3, iron: 5.4, vitaminC: 0, category: 'protein' },
        'tempeh': { calories: 192, protein: 20, fiber: 7.0, iron: 2.7, vitaminC: 0, category: 'protein' },
        'lentils': { calories: 116, protein: 9, fiber: 8.0, iron: 3.3, vitaminC: 1.5, category: 'protein' },
        'chickpeas': { calories: 164, protein: 8.9, fiber: 7.6, iron: 2.9, vitaminC: 1.3, category: 'protein' },
        'beans': { calories: 127, protein: 8.7, fiber: 6.4, iron: 2.1, vitaminC: 0, category: 'protein' },
        'eggs': { calories: 155, protein: 13, fiber: 0, iron: 1.8, vitaminC: 0, category: 'protein' },
        'cheese': { calories: 402, protein: 25, fiber: 0, iron: 0.7, vitaminC: 0, category: 'dairy' },
        'rice': { calories: 130, protein: 2.7, fiber: 0.4, iron: 0.2, vitaminC: 0, category: 'grain' },
        'quinoa': { calories: 120, protein: 4.4, fiber: 2.8, iron: 1.5, vitaminC: 0, category: 'grain' },
        'broccoli': { calories: 34, protein: 2.8, fiber: 2.6, iron: 0.7, vitaminC: 89, category: 'vegetable' },
        'spinach': { calories: 23, protein: 2.9, fiber: 2.2, iron: 2.7, vitaminC: 28, category: 'vegetable' },
        'sweet potato': { calories: 86, protein: 1.6, fiber: 3.0, iron: 0.6, vitaminC: 2.4, category: 'vegetable' },
        'avocado': { calories: 160, protein: 2, fiber: 6.7, iron: 0.6, vitaminC: 10, category: 'vegetable' },
    };

    // Sustainable substitution suggestions
    const substitutions = {
        'beef': [
            { replacement: 'lentils', reason: 'Lentils provide excellent protein and fiber with 97% less carbon emissions than beef.' },
            { replacement: 'mushrooms', reason: 'Mushrooms offer a rich umami flavor similar to beef with 98% less carbon impact.' },
            { replacement: 'tempeh', reason: 'Tempeh has a meaty texture with 20g protein per 100g and 93% less emissions.' },
            { replacement: 'beans', reason: 'Beans are a hearty, affordable protein source with 97% fewer emissions.' },
            { replacement: 'tofu', reason: 'Tofu is versatile and absorbs flavors well, with 93% lower carbon footprint.' },
            { replacement: 'seitan', reason: 'Seitan has a chewy, meat-like texture and 28g protein per 100g with 94% less CO₂.' },
            { replacement: 'jackfruit', reason: 'Young jackfruit shreds like pulled beef and absorbs marinades beautifully.' },
            { replacement: 'black beans', reason: 'Black beans work perfectly in tacos, chili, and burgers with 97% fewer emissions.' },
        ],
        'lamb': [
            { replacement: 'chickpeas', reason: 'Chickpeas provide satisfying texture and protein with 97% less emissions.' },
            { replacement: 'lentils', reason: 'Lentils can replicate the heartiness of lamb dishes with 96% carbon savings.' },
            { replacement: 'seitan', reason: 'Seitan offers a chewy, meat-like texture with 94% lower footprint.' },
            { replacement: 'mushrooms', reason: 'A mix of mushrooms provides deep, earthy flavors similar to lamb.' },
            { replacement: 'black beans', reason: 'Black beans create rich, hearty curries and stews as a lamb replacement.' },
            { replacement: 'tempeh', reason: 'Marinated tempeh absorbs spices well, great in curries and kebabs.' },
        ],
        'pork': [
            { replacement: 'jackfruit', reason: 'Jackfruit has a pulled-pork-like texture and is very low impact.' },
            { replacement: 'tempeh', reason: 'Tempeh provides similar protein levels with 76% less emissions.' },
            { replacement: 'mushrooms', reason: 'Mushrooms provide savory umami flavor with 92% less carbon.' },
            { replacement: 'seitan', reason: 'Seitan mimics pork in stir-fries and dumplings with great chew.' },
            { replacement: 'tofu', reason: 'Pressed and pan-fried tofu works in many pork-based dishes with 74% less CO₂.' },
            { replacement: 'lentils', reason: 'Lentils make excellent ground-pork substitutes in meat sauces.' },
        ],
        'chicken': [
            { replacement: 'tofu', reason: 'Tofu is a versatile, lower-carbon protein alternative with 71% less emissions.' },
            { replacement: 'chickpeas', reason: 'Chickpeas work great in curries and salads, with 88% less carbon.' },
            { replacement: 'tempeh', reason: 'Tempeh offers comparable protein with a firm texture and 74% savings.' },
            { replacement: 'seitan', reason: 'Seitan is the closest plant texture to chicken breast, with 78% less CO₂.' },
            { replacement: 'jackfruit', reason: 'Shredded jackfruit mimics pulled chicken in sandwiches and tacos.' },
            { replacement: 'cauliflower', reason: 'Roasted cauliflower steaks or wings offer a satisfying, low-carbon option.' },
            { replacement: 'white beans', reason: 'White beans blend into creamy chicken-style soups and casseroles.' },
        ],
        'turkey': [
            { replacement: 'lentils', reason: 'Seasoned lentils make a great ground-turkey substitute in pasta and tacos.' },
            { replacement: 'chickpeas', reason: 'Mashed chickpeas create protein-rich patties and fillings.' },
            { replacement: 'tempeh', reason: 'Crumbled tempeh works perfectly as a turkey substitute with added probiotics.' },
            { replacement: 'mushrooms', reason: 'Finely diced mushrooms mixed with grains replicate turkey mince.' },
        ],
        'shrimp': [
            { replacement: 'hearts of palm', reason: 'Hearts of palm mimic shrimp texture with dramatically lower carbon footprint.' },
            { replacement: 'chickpeas', reason: 'Crispy roasted chickpeas can substitute in many shrimp dishes.' },
            { replacement: 'king oyster mushrooms', reason: 'Sliced king oyster mushrooms mimic the bite of shrimp beautifully.' },
            { replacement: 'white beans', reason: 'White beans add protein and body to shrimp-style pastas and soups.' },
        ],
        'prawns': [
            { replacement: 'king oyster mushrooms', reason: 'Sliced king oyster mushrooms can mimic prawn texture beautifully.' },
            { replacement: 'hearts of palm', reason: 'Hearts of palm have a mild, seafood-like flavor with 95% less carbon.' },
            { replacement: 'tofu', reason: 'Firm tofu cubes marinated in nori and lemon mimic prawn flavor.' },
        ],
        'salmon': [
            { replacement: 'marinated tofu', reason: 'Marinated and baked tofu can mimic salmon texture with 63% less carbon.' },
            { replacement: 'carrots', reason: 'Slow-roasted marinated carrots create a surprising "salmon" fillet effect.' },
            { replacement: 'chickpeas', reason: 'Mashed chickpeas with nori and capers make great salmon-style patties.' },
        ],
        'tuna': [
            { replacement: 'chickpeas', reason: 'Mashed chickpeas with lemon and capers mimic tuna salad perfectly.' },
            { replacement: 'jackfruit', reason: 'Flaked jackfruit has a tuna-like texture for sandwiches and wraps.' },
            { replacement: 'white beans', reason: 'White beans blended with nori create a tuna-style spread.' },
        ],
        'cod': [
            { replacement: 'tofu', reason: 'Beer-battered tofu works as a cod substitute in fish and chips.' },
            { replacement: 'hearts of palm', reason: 'Hearts of palm flake like white fish with much lower impact.' },
            { replacement: 'cauliflower', reason: 'Battered cauliflower steaks make a hearty cod replacement.' },
        ],
        'fish': [
            { replacement: 'tofu', reason: 'Tofu marinated with seaweed captures a mild fish flavor sustainably.' },
            { replacement: 'banana blossom', reason: 'Banana blossom has a flaky, fish-like texture when battered and fried.' },
            { replacement: 'jackfruit', reason: 'Young jackfruit shreds like fish for tacos and curries.' },
        ],
        'cheese': [
            { replacement: 'nutritional yeast', reason: 'Nutritional yeast provides a cheesy flavor with 95% less emissions.' },
            { replacement: 'cashew cream', reason: 'Blended cashews create creamy sauces with 81% less carbon impact.' },
            { replacement: 'avocado', reason: 'Avocado adds creaminess to sandwiches and toast as a cheese swap.' },
            { replacement: 'hummus', reason: 'Hummus provides creamy, protein-rich richness in wraps and sandwiches.' },
            { replacement: 'tofu', reason: 'Blended silken tofu mimics ricotta and cream cheese textures.' },
        ],
        'butter': [
            { replacement: 'olive oil', reason: 'Olive oil is heart-healthy and has 71% less carbon footprint than butter.' },
            { replacement: 'avocado', reason: 'Mashed avocado works as a spread with 89% less emissions.' },
            { replacement: 'coconut oil', reason: 'Coconut oil works for baking and frying with 73% less carbon than butter.' },
            { replacement: 'tahini', reason: 'Tahini adds richness as a butter replacement in dressings and baking.' },
        ],
        'cream': [
            { replacement: 'coconut cream', reason: 'Coconut cream offers richness with 84% less carbon impact.' },
            { replacement: 'cashew cream', reason: 'Blended cashews create a silky cream alternative.' },
            { replacement: 'oat cream', reason: 'Oat-based cream is neutral-flavored and great for savory dishes.' },
            { replacement: 'silken tofu', reason: 'Blended silken tofu makes a protein-rich, creamy base for sauces.' },
        ],
        'milk': [
            { replacement: 'oat milk', reason: 'Oat milk has a creamy texture with 72% less emissions than dairy milk.' },
            { replacement: 'soy milk', reason: 'Soy milk matches dairy milk in protein with 69% less carbon.' },
            { replacement: 'almond milk', reason: 'Almond milk is light and nutty with 78% less emissions.' },
        ],
        'yogurt': [
            { replacement: 'coconut yogurt', reason: 'Coconut yogurt is rich and creamy with 60% less carbon emissions.' },
            { replacement: 'soy yogurt', reason: 'Soy yogurt matches dairy yogurt in protein with lower impact.' },
            { replacement: 'oat yogurt', reason: 'Oat yogurt has a mild, neutral flavor great for granola bowls.' },
        ],
        'rice': [
            { replacement: 'quinoa', reason: 'Quinoa has more protein and fiber with 56% less carbon than rice.' },
            { replacement: 'couscous', reason: 'Couscous cooks faster and has 52% less emissions.' },
            { replacement: 'cauliflower rice', reason: 'Grated cauliflower is a low-carb, ultra-low-carbon rice alternative.' },
            { replacement: 'bulgur', reason: 'Bulgur wheat is nutritious, quick-cooking, and lower impact than rice.' },
            { replacement: 'lentils', reason: 'Lentils can replace rice as a base, adding protein and fiber.' },
        ],
        'bacon': [
            { replacement: 'smoked tempeh', reason: 'Smoked tempeh provides a smoky, savory flavor with far less carbon.' },
            { replacement: 'coconut bacon', reason: 'Toasted coconut flakes with liquid smoke create a crispy, smoky topping.' },
            { replacement: 'mushrooms', reason: 'Thinly sliced and roasted shiitake mushrooms make crispy "bacon" strips.' },
            { replacement: 'smoked tofu', reason: 'Thin-sliced smoked tofu crisps up beautifully as a bacon replacement.' },
        ],
        'sausage': [
            { replacement: 'tempeh', reason: 'Seasoned crumbled tempeh replicates sausage in pasta dishes and pizzas.' },
            { replacement: 'mushrooms', reason: 'Finely diced mushrooms with Italian spices mimic sausage crumbles.' },
            { replacement: 'lentils', reason: 'Spiced lentils make hearty sausage-style fillings for rolls and casseroles.' },
            { replacement: 'beans', reason: 'Mashed beans with smoked paprika create a sausage-like patty base.' },
        ],
        'ham': [
            { replacement: 'smoked tofu', reason: 'Smoked tofu slices thin like ham with a similar savory, smoky flavor.' },
            { replacement: 'tempeh', reason: 'Marinated and smoked tempeh slices work in sandwiches and salads.' },
            { replacement: 'mushrooms', reason: 'Roasted portobello slices offer a meaty texture for ham-style dishes.' },
        ],
        'salami': [
            { replacement: 'smoked tofu', reason: 'Thin-sliced smoked tofu has a firm bite similar to salami.' },
            { replacement: 'mushrooms', reason: 'Dried and seasoned mushroom slices can mimic salami on charcuterie.' },
        ],
        'eggs': [
            { replacement: 'flax eggs', reason: 'Ground flax + water works as a binder in baking with much lower impact.' },
            { replacement: 'tofu scramble', reason: 'Seasoned crumbled tofu makes a great scrambled egg substitute.' },
            { replacement: 'chickpea flour', reason: 'Chickpea flour omelettes are protein-rich and naturally egg-free.' },
            { replacement: 'chia eggs', reason: 'Chia seeds mixed with water provide binding power for baking.' },
        ],
        'pasta': [
            { replacement: 'lentil pasta', reason: 'Lentil-based pasta doubles the protein and adds fiber with similar taste.' },
            { replacement: 'zucchini noodles', reason: 'Spiralized zucchini is ultra-low-carbon and adds vegetable servings.' },
            { replacement: 'chickpea pasta', reason: 'Chickpea pasta provides 25g protein per serving with a mild taste.' },
        ],
        'chocolate': [
            { replacement: 'carob', reason: 'Carob powder is naturally sweet with 76% less carbon than chocolate.' },
            { replacement: 'cocoa nibs', reason: 'Raw cocoa nibs use less processing and provide intense chocolate flavor.' },
        ],
        'coffee': [
            { replacement: 'chicory root', reason: 'Roasted chicory root brews like coffee with 85% less carbon footprint.' },
            { replacement: 'tea', reason: 'Tea has 85% less carbon footprint and provides a gentle caffeine boost.' },
        ],
        'ice cream': [
            { replacement: 'banana ice cream', reason: 'Frozen blended bananas create creamy soft-serve with minimal carbon impact.' },
            { replacement: 'coconut ice cream', reason: 'Coconut milk-based ice cream is rich and creamy with less environmental cost.' },
        ],
    };

    // Health benefit tags
    const healthBenefits = {
        'lentils': ['high fiber', 'iron-rich', 'heart healthy', 'low fat'],
        'chickpeas': ['high fiber', 'B vitamins', 'mineral-rich', 'blood sugar control'],
        'beans': ['high fiber', 'protein-rich', 'heart healthy', 'weight management'],
        'black beans': ['high fiber', 'antioxidants', 'iron-rich', 'heart healthy'],
        'white beans': ['high fiber', 'protein-rich', 'low fat', 'mineral-rich'],
        'tofu': ['complete protein', 'calcium-rich', 'low calorie', 'isoflavones'],
        'tempeh': ['probiotics', 'high protein', 'bone health', 'B12 (fermented)'],
        'seitan': ['very high protein', 'low fat', 'iron-rich', 'meat-like texture'],
        'quinoa': ['complete protein', 'gluten-free', 'mineral-rich', 'high fiber'],
        'spinach': ['iron-rich', 'vitamin K', 'antioxidants', 'eye health'],
        'broccoli': ['vitamin C', 'cancer-fighting', 'fiber', 'vitamin K'],
        'cauliflower': ['vitamin C', 'low calorie', 'choline-rich', 'anti-inflammatory'],
        'sweet potato': ['vitamin A', 'antioxidants', 'fiber', 'blood sugar regulation'],
        'oats': ['cholesterol-lowering', 'fiber', 'sustained energy', 'B vitamins'],
        'mushrooms': ['vitamin D', 'immune support', 'low calorie', 'B vitamins'],
        'avocado': ['healthy fats', 'potassium', 'fiber', 'heart healthy'],
        'walnuts': ['omega-3', 'brain health', 'antioxidants', 'heart healthy'],
        'olive oil': ['monounsaturated fats', 'anti-inflammatory', 'heart healthy', 'antioxidants'],
        'jackfruit': ['vitamin C', 'potassium', 'high fiber', 'low calorie'],
        'hummus': ['high fiber', 'plant protein', 'iron-rich', 'heart healthy'],
        'tahini': ['calcium-rich', 'healthy fats', 'iron-rich', 'anti-inflammatory'],
        'oat milk': ['beta-glucan', 'cholesterol-lowering', 'B vitamins', 'low fat'],
        'soy milk': ['complete protein', 'isoflavones', 'bone health', 'B vitamins'],
        'almond milk': ['vitamin E', 'low calorie', 'dairy-free', 'bone health'],
        'coconut cream': ['healthy fats', 'mineral-rich', 'dairy-free', 'energy boost'],
        'cashew cream': ['healthy fats', 'magnesium', 'copper-rich', 'immune support'],
        'nutritional yeast': ['B12 fortified', 'complete protein', 'zinc-rich', 'low calorie'],
        'flax eggs': ['omega-3', 'fiber', 'lignans', 'hormone balance'],
        'chia eggs': ['omega-3', 'fiber', 'calcium-rich', 'antioxidants'],
        'smoked tempeh': ['probiotics', 'high protein', 'smoky flavor', 'B vitamins'],
        'smoked tofu': ['high protein', 'calcium-rich', 'low fat', 'smoky flavor'],
        'coconut oil': ['medium-chain fats', 'antimicrobial', 'energy boost', 'skin health'],
        'hearts of palm': ['low calorie', 'potassium', 'vitamin C', 'high fiber'],
        'king oyster mushrooms': ['vitamin D', 'antioxidants', 'low calorie', 'immune support'],
        'banana blossom': ['low calorie', 'vitamin C', 'potassium', 'high fiber'],
        'chickpea flour': ['high protein', 'gluten-free', 'iron-rich', 'high fiber'],
        'lentil pasta': ['high protein', 'high fiber', 'iron-rich', 'gluten-free option'],
        'zucchini noodles': ['ultra-low calorie', 'vitamin C', 'potassium', 'hydrating'],
        'chickpea pasta': ['high protein', 'high fiber', 'mineral-rich', 'gluten-free'],
        'carob': ['calcium-rich', 'caffeine-free', 'antioxidants', 'high fiber'],
        'coconut yogurt': ['probiotics', 'dairy-free', 'medium-chain fats', 'gut health'],
        'soy yogurt': ['complete protein', 'probiotics', 'isoflavones', 'bone health'],
        'oat yogurt': ['beta-glucan', 'probiotics', 'low fat', 'gut health'],
        'bulgur': ['high fiber', 'manganese', 'iron-rich', 'low glycemic'],
        'cauliflower rice': ['ultra-low calorie', 'vitamin C', 'low carb', 'antioxidants'],
        'coconut bacon': ['medium-chain fats', 'iron-rich', 'dairy-free', 'crunchy fiber'],
        'silken tofu': ['complete protein', 'calcium-rich', 'low calorie', 'versatile'],
        'oat cream': ['beta-glucan', 'low fat', 'cholesterol-lowering', 'dairy-free'],
        'carrots': ['vitamin A', 'antioxidants', 'eye health', 'low calorie'],
        'banana ice cream': ['potassium', 'natural sugars', 'dairy-free', 'B6 vitamins'],
        'coconut ice cream': ['medium-chain fats', 'dairy-free', 'mineral-rich', 'energy boost'],
        'chicory root': ['inulin fiber', 'prebiotic', 'caffeine-free', 'gut health'],
        'tea': ['antioxidants', 'L-theanine', 'hydrating', 'metabolism boost'],
        'cocoa nibs': ['antioxidants', 'magnesium', 'iron-rich', 'mood boost'],
        'marinated tofu': ['complete protein', 'calcium-rich', 'low calorie', 'versatile'],
        'tofu scramble': ['complete protein', 'calcium-rich', 'low calorie', 'cholesterol-free'],
    };

    // Sample recipes database
    const sampleRecipes = [
        {
            id: 1,
            name: 'Classic Beef Bolognese',
            image: 'https://images.unsplash.com/photo-1622973536968-3ead9e780960?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'beef', amount: 500, unit: 'g' },
                { name: 'tomatoes', amount: 400, unit: 'g' },
                { name: 'onions', amount: 150, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
                { name: 'olive oil', amount: 30, unit: 'ml' },
                { name: 'pasta', amount: 400, unit: 'g' },
                { name: 'cheese', amount: 50, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Italian',
            time: '45 min',
        },
        {
            id: 2,
            name: 'Chicken Stir-Fry',
            image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'chicken', amount: 400, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'broccoli', amount: 200, unit: 'g' },
                { name: 'peppers', amount: 150, unit: 'g' },
                { name: 'soy sauce', amount: 30, unit: 'ml' },
                { name: 'garlic', amount: 10, unit: 'g' },
                { name: 'ginger', amount: 10, unit: 'g' },
                { name: 'vegetable oil', amount: 20, unit: 'ml' },
            ],
            servings: 3,
            cuisine: 'Asian',
            time: '25 min',
        },
        {
            id: 3,
            name: 'Lamb Curry',
            image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'lamb', amount: 500, unit: 'g' },
                { name: 'onions', amount: 200, unit: 'g' },
                { name: 'tomatoes', amount: 300, unit: 'g' },
                { name: 'garlic', amount: 15, unit: 'g' },
                { name: 'ginger', amount: 15, unit: 'g' },
                { name: 'cream', amount: 100, unit: 'ml' },
                { name: 'rice', amount: 300, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Indian',
            time: '60 min',
        },
        {
            id: 4,
            name: 'Salmon with Buttered Vegetables',
            image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'salmon', amount: 400, unit: 'g' },
                { name: 'butter', amount: 40, unit: 'g' },
                { name: 'potatoes', amount: 400, unit: 'g' },
                { name: 'broccoli', amount: 200, unit: 'g' },
                { name: 'lemon', amount: 50, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
            ],
            servings: 2,
            cuisine: 'European',
            time: '35 min',
        },
        {
            id: 5,
            name: 'Bacon Cheeseburger',
            image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'beef', amount: 400, unit: 'g' },
                { name: 'bacon', amount: 100, unit: 'g' },
                { name: 'cheese', amount: 80, unit: 'g' },
                { name: 'bread', amount: 200, unit: 'g' },
                { name: 'lettuce', amount: 50, unit: 'g' },
                { name: 'tomatoes', amount: 100, unit: 'g' },
                { name: 'onions', amount: 50, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'American',
            time: '20 min',
        },
        {
            id: 10,
            name: 'Thai Peanut Tofu Stir-Fry',
            image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'tofu', amount: 300, unit: 'g' },
                { name: 'broccoli', amount: 200, unit: 'g' },
                { name: 'peppers', amount: 150, unit: 'g' },
                { name: 'carrots', amount: 100, unit: 'g' },
                { name: 'peanuts', amount: 50, unit: 'g' },
                { name: 'soy sauce', amount: 30, unit: 'ml' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'ginger', amount: 10, unit: 'g' },
            ],
            servings: 3,
            cuisine: 'Thai',
            time: '25 min',
        },
        {
            id: 12,
            name: 'Mushroom Risotto',
            image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'rice', amount: 350, unit: 'g' },
                { name: 'mushrooms', amount: 250, unit: 'g' },
                { name: 'onions', amount: 100, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
                { name: 'olive oil', amount: 30, unit: 'ml' },
                { name: 'spinach', amount: 80, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Italian',
            time: '35 min',
        },
        // === Asian Meals ===
        {
            id: 13,
            name: 'Chicken Biryani',
            image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'chicken', amount: 500, unit: 'g' },
                { name: 'rice', amount: 400, unit: 'g' },
                { name: 'butter', amount: 40, unit: 'g' },
                { name: 'onions', amount: 200, unit: 'g' },
                { name: 'yogurt', amount: 100, unit: 'g' },
                { name: 'garlic', amount: 15, unit: 'g' },
                { name: 'ginger', amount: 15, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Indian',
            time: '60 min',
        },
        {
            id: 14,
            name: 'Chicken Tikka Masala',
            image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'chicken', amount: 500, unit: 'g' },
                { name: 'cream', amount: 150, unit: 'ml' },
                { name: 'tomatoes', amount: 300, unit: 'g' },
                { name: 'onions', amount: 150, unit: 'g' },
                { name: 'butter', amount: 30, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
                { name: 'ginger', amount: 10, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Indian',
            time: '45 min',
        },
        {
            id: 15,
            name: 'Butter Chicken',
            image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'chicken', amount: 500, unit: 'g' },
                { name: 'butter', amount: 60, unit: 'g' },
                { name: 'cream', amount: 200, unit: 'ml' },
                { name: 'tomatoes', amount: 400, unit: 'g' },
                { name: 'onions', amount: 150, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'garlic', amount: 15, unit: 'g' },
                { name: 'ginger', amount: 15, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Indian',
            time: '50 min',
        },
        {
            id: 16,
            name: 'Thai Massaman Beef Curry',
            image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'beef', amount: 500, unit: 'g' },
                { name: 'potatoes', amount: 300, unit: 'g' },
                { name: 'coconut milk', amount: 400, unit: 'ml' },
                { name: 'onions', amount: 150, unit: 'g' },
                { name: 'peanuts', amount: 50, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'ginger', amount: 10, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Thai',
            time: '55 min',
        },
        {
            id: 17,
            name: 'Korean Beef Bibimbap',
            image: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'beef', amount: 300, unit: 'g' },
                { name: 'rice', amount: 400, unit: 'g' },
                { name: 'eggs', amount: 120, unit: 'g' },
                { name: 'spinach', amount: 100, unit: 'g' },
                { name: 'carrots', amount: 100, unit: 'g' },
                { name: 'mushrooms', amount: 100, unit: 'g' },
                { name: 'soy sauce', amount: 30, unit: 'ml' },
            ],
            servings: 3,
            cuisine: 'Korean',
            time: '35 min',
        },
        {
            id: 18,
            name: 'Japanese Pork Ramen',
            image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'pork', amount: 400, unit: 'g' },
                { name: 'eggs', amount: 120, unit: 'g' },
                { name: 'corn', amount: 100, unit: 'g' },
                { name: 'spinach', amount: 80, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
                { name: 'ginger', amount: 10, unit: 'g' },
                { name: 'soy sauce', amount: 30, unit: 'ml' },
            ],
            servings: 3,
            cuisine: 'Japanese',
            time: '45 min',
        },
        {
            id: 19,
            name: 'Shrimp Pad Thai',
            image: 'images/thai_shrimp.png',
            ingredients: [
                { name: 'shrimp', amount: 300, unit: 'g' },
                { name: 'eggs', amount: 100, unit: 'g' },
                { name: 'rice', amount: 200, unit: 'g' },
                { name: 'peanuts', amount: 40, unit: 'g' },
                { name: 'carrots', amount: 80, unit: 'g' },
                { name: 'lime', amount: 30, unit: 'g' },
                { name: 'soy sauce', amount: 20, unit: 'ml' },
            ],
            servings: 3,
            cuisine: 'Thai',
            time: '25 min',
        },
        {
            id: 20,
            name: 'Chinese Sweet and Sour Chicken',
            image: 'images/Chinese Sweet and Sour Chicken.png',
            ingredients: [
                { name: 'chicken', amount: 400, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'peppers', amount: 150, unit: 'g' },
                { name: 'pineapple', amount: 150, unit: 'g' },
                { name: 'onions', amount: 100, unit: 'g' },
                { name: 'sugar', amount: 30, unit: 'g' },
                { name: 'vegetable oil', amount: 30, unit: 'ml' },
            ],
            servings: 3,
            cuisine: 'Chinese',
            time: '30 min',
        },
        {
            id: 21,
            name: 'Vietnamese Beef Pho',
            image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'beef', amount: 400, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'onions', amount: 150, unit: 'g' },
                { name: 'ginger', amount: 20, unit: 'g' },
                { name: 'spinach', amount: 80, unit: 'g' },
                { name: 'lime', amount: 30, unit: 'g' },
                { name: 'soy sauce', amount: 20, unit: 'ml' },
            ],
            servings: 4,
            cuisine: 'Vietnamese',
            time: '50 min',
        },
        {
            id: 22,
            name: 'Chicken Katsu Curry',
            image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'chicken', amount: 400, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'eggs', amount: 100, unit: 'g' },
                { name: 'potatoes', amount: 200, unit: 'g' },
                { name: 'onions', amount: 100, unit: 'g' },
                { name: 'carrots', amount: 80, unit: 'g' },
                { name: 'flour', amount: 50, unit: 'g' },
            ],
            servings: 3,
            cuisine: 'Japanese',
            time: '40 min',
        },
        {
            id: 23,
            name: 'Thai Red Curry with Shrimp',
            image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'shrimp', amount: 350, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'coconut milk', amount: 400, unit: 'ml' },
                { name: 'peppers', amount: 100, unit: 'g' },
                { name: 'broccoli', amount: 100, unit: 'g' },
                { name: 'ginger', amount: 10, unit: 'g' },
                { name: 'lime', amount: 20, unit: 'g' },
            ],
            servings: 3,
            cuisine: 'Thai',
            time: '30 min',
        },
        {
            id: 24,
            name: 'Lamb Rogan Josh',
            image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'lamb', amount: 500, unit: 'g' },
                { name: 'cream', amount: 100, unit: 'ml' },
                { name: 'tomatoes', amount: 300, unit: 'g' },
                { name: 'onions', amount: 200, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'garlic', amount: 15, unit: 'g' },
                { name: 'ginger', amount: 15, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Indian',
            time: '65 min',
        },
        {
            id: 25,
            name: 'Indonesian Nasi Goreng',
            image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'chicken', amount: 250, unit: 'g' },
                { name: 'shrimp', amount: 150, unit: 'g' },
                { name: 'rice', amount: 400, unit: 'g' },
                { name: 'eggs', amount: 120, unit: 'g' },
                { name: 'cabbage', amount: 100, unit: 'g' },
                { name: 'soy sauce', amount: 30, unit: 'ml' },
                { name: 'garlic', amount: 10, unit: 'g' },
            ],
            servings: 3,
            cuisine: 'Indonesian',
            time: '25 min',
        },
        {
            id: 26,
            name: 'Lamb Biryani',
            image: 'images/lamb biriyani.png',
            ingredients: [
                { name: 'lamb', amount: 500, unit: 'g' },
                { name: 'rice', amount: 400, unit: 'g' },
                { name: 'butter', amount: 40, unit: 'g' },
                { name: 'onions', amount: 200, unit: 'g' },
                { name: 'yogurt', amount: 100, unit: 'g' },
                { name: 'garlic', amount: 15, unit: 'g' },
                { name: 'ginger', amount: 15, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Indian',
            time: '70 min',
        },
        {
            id: 27,
            name: 'Chinese Kung Pao Chicken',
            image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'chicken', amount: 400, unit: 'g' },
                { name: 'peanuts', amount: 60, unit: 'g' },
                { name: 'peppers', amount: 150, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'soy sauce', amount: 30, unit: 'ml' },
                { name: 'garlic', amount: 10, unit: 'g' },
                { name: 'ginger', amount: 10, unit: 'g' },
            ],
            servings: 3,
            cuisine: 'Chinese',
            time: '30 min',
        },
        {
            id: 28,
            name: 'Japanese Chicken Teriyaki',
            image: 'images/japanese chicken terriyaki.png',
            ingredients: [
                { name: 'chicken', amount: 450, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'broccoli', amount: 150, unit: 'g' },
                { name: 'soy sauce', amount: 40, unit: 'ml' },
                { name: 'sugar', amount: 20, unit: 'g' },
                { name: 'ginger', amount: 10, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
            ],
            servings: 3,
            cuisine: 'Japanese',
            time: '30 min',
        },
        {
            id: 29,
            name: 'Malaysian Chicken Satay',
            image: 'https://images.unsplash.com/photo-1529563021893-cc83c992d75d?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'chicken', amount: 500, unit: 'g' },
                { name: 'peanuts', amount: 80, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'coconut milk', amount: 100, unit: 'ml' },
                { name: 'soy sauce', amount: 20, unit: 'ml' },
                { name: 'garlic', amount: 10, unit: 'g' },
                { name: 'ginger', amount: 10, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Malaysian',
            time: '35 min',
        },
        {
            id: 30,
            name: 'Thai Green Curry with Chicken',
            image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'chicken', amount: 400, unit: 'g' },
                { name: 'coconut milk', amount: 400, unit: 'ml' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'peppers', amount: 100, unit: 'g' },
                { name: 'broccoli', amount: 100, unit: 'g' },
                { name: 'ginger', amount: 10, unit: 'g' },
                { name: 'lime', amount: 20, unit: 'g' },
            ],
            servings: 3,
            cuisine: 'Thai',
            time: '30 min',
        },
        {
            id: 31,
            name: 'Beef Rendang',
            image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'beef', amount: 600, unit: 'g' },
                { name: 'coconut milk', amount: 400, unit: 'ml' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'onions', amount: 150, unit: 'g' },
                { name: 'garlic', amount: 15, unit: 'g' },
                { name: 'ginger', amount: 15, unit: 'g' },
                { name: 'lemon', amount: 20, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Indonesian',
            time: '90 min',
        },
        {
            id: 32,
            name: 'Prawn Fried Rice',
            image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'prawns', amount: 300, unit: 'g' },
                { name: 'rice', amount: 400, unit: 'g' },
                { name: 'eggs', amount: 100, unit: 'g' },
                { name: 'peas', amount: 80, unit: 'g' },
                { name: 'carrots', amount: 80, unit: 'g' },
                { name: 'soy sauce', amount: 30, unit: 'ml' },
                { name: 'vegetable oil', amount: 20, unit: 'ml' },
            ],
            servings: 3,
            cuisine: 'Chinese',
            time: '20 min',
        },
        // === Vegetarian Meals with Dairy ===
        {
            id: 33,
            name: 'Classic Mac and Cheese',
            image: 'https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'cheese', amount: 200, unit: 'g' },
                { name: 'butter', amount: 50, unit: 'g' },
                { name: 'milk', amount: 300, unit: 'ml' },
                { name: 'pasta', amount: 400, unit: 'g' },
                { name: 'flour', amount: 30, unit: 'g' },
                { name: 'onions', amount: 50, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'American',
            time: '30 min',
        },
        {
            id: 34,
            name: 'Spinach and Cheese Lasagna',
            image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'cheese', amount: 250, unit: 'g' },
                { name: 'cream', amount: 150, unit: 'ml' },
                { name: 'eggs', amount: 100, unit: 'g' },
                { name: 'spinach', amount: 300, unit: 'g' },
                { name: 'pasta', amount: 300, unit: 'g' },
                { name: 'butter', amount: 30, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
            ],
            servings: 6,
            cuisine: 'Italian',
            time: '60 min',
        },
        {
            id: 35,
            name: 'Vegetable Quiche',
            image: 'https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'eggs', amount: 200, unit: 'g' },
                { name: 'butter', amount: 60, unit: 'g' },
                { name: 'cheese', amount: 100, unit: 'g' },
                { name: 'cream', amount: 100, unit: 'ml' },
                { name: 'flour', amount: 200, unit: 'g' },
                { name: 'broccoli', amount: 150, unit: 'g' },
                { name: 'onions', amount: 100, unit: 'g' },
                { name: 'mushrooms', amount: 100, unit: 'g' },
            ],
            servings: 6,
            cuisine: 'French',
            time: '55 min',
        },
        {
            id: 36,
            name: 'Eggplant Parmesan',
            image: 'images/eggplant parmesan.png',
            ingredients: [
                { name: 'eggplant', amount: 500, unit: 'g' },
                { name: 'cheese', amount: 200, unit: 'g' },
                { name: 'eggs', amount: 100, unit: 'g' },
                { name: 'tomatoes', amount: 400, unit: 'g' },
                { name: 'flour', amount: 80, unit: 'g' },
                { name: 'olive oil', amount: 40, unit: 'ml' },
                { name: 'garlic', amount: 10, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Italian',
            time: '50 min',
        },
        {
            id: 37,
            name: 'Mushroom and Cheese Omelette',
            image: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'eggs', amount: 240, unit: 'g' },
                { name: 'cheese', amount: 80, unit: 'g' },
                { name: 'butter', amount: 20, unit: 'g' },
                { name: 'mushrooms', amount: 100, unit: 'g' },
                { name: 'spinach', amount: 50, unit: 'g' },
                { name: 'milk', amount: 30, unit: 'ml' },
            ],
            servings: 2,
            cuisine: 'French',
            time: '15 min',
        },
        {
            id: 38,
            name: 'Creamy Broccoli and Cheese Soup',
            image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'broccoli', amount: 400, unit: 'g' },
                { name: 'cheese', amount: 150, unit: 'g' },
                { name: 'cream', amount: 150, unit: 'ml' },
                { name: 'butter', amount: 30, unit: 'g' },
                { name: 'milk', amount: 200, unit: 'ml' },
                { name: 'onions', amount: 100, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'American',
            time: '30 min',
        },
        {
            id: 39,
            name: 'Paneer Butter Masala',
            image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'cheese', amount: 300, unit: 'g' },
                { name: 'butter', amount: 50, unit: 'g' },
                { name: 'cream', amount: 100, unit: 'ml' },
                { name: 'tomatoes', amount: 300, unit: 'g' },
                { name: 'onions', amount: 150, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
                { name: 'ginger', amount: 10, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Indian',
            time: '40 min',
        },
        {
            id: 40,
            name: 'Creamy Mushroom Pasta',
            image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'mushrooms', amount: 300, unit: 'g' },
                { name: 'cream', amount: 200, unit: 'ml' },
                { name: 'butter', amount: 30, unit: 'g' },
                { name: 'cheese', amount: 60, unit: 'g' },
                { name: 'pasta', amount: 400, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
                { name: 'onions', amount: 80, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Italian',
            time: '25 min',
        },
        {
            id: 41,
            name: 'Vegetable Fried Rice with Egg',
            image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'rice', amount: 400, unit: 'g' },
                { name: 'eggs', amount: 120, unit: 'g' },
                { name: 'carrots', amount: 80, unit: 'g' },
                { name: 'peas', amount: 80, unit: 'g' },
                { name: 'corn', amount: 80, unit: 'g' },
                { name: 'soy sauce', amount: 30, unit: 'ml' },
                { name: 'vegetable oil', amount: 20, unit: 'ml' },
            ],
            servings: 3,
            cuisine: 'Asian',
            time: '20 min',
        },
        {
            id: 42,
            name: 'Greek Spanakopita',
            image: 'images/greek spanakopita.png',
            ingredients: [
                { name: 'cheese', amount: 200, unit: 'g' },
                { name: 'butter', amount: 80, unit: 'g' },
                { name: 'eggs', amount: 100, unit: 'g' },
                { name: 'spinach', amount: 400, unit: 'g' },
                { name: 'flour', amount: 200, unit: 'g' },
                { name: 'onions', amount: 80, unit: 'g' },
            ],
            servings: 6,
            cuisine: 'Greek',
            time: '50 min',
        },
        {
            id: 43,
            name: 'Four Cheese Pizza',
            image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'cheese', amount: 300, unit: 'g' },
                { name: 'flour', amount: 300, unit: 'g' },
                { name: 'tomatoes', amount: 200, unit: 'g' },
                { name: 'olive oil', amount: 30, unit: 'ml' },
                { name: 'eggs', amount: 50, unit: 'g' },
                { name: 'sugar', amount: 10, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Italian',
            time: '40 min',
        },
        {
            id: 44,
            name: 'French Onion Soup',
            image: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'onions', amount: 600, unit: 'g' },
                { name: 'cheese', amount: 150, unit: 'g' },
                { name: 'butter', amount: 50, unit: 'g' },
                { name: 'bread', amount: 150, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
                { name: 'olive oil', amount: 20, unit: 'ml' },
            ],
            servings: 4,
            cuisine: 'French',
            time: '50 min',
        },
        {
            id: 45,
            name: 'Cream of Tomato Soup',
            image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'tomatoes', amount: 600, unit: 'g' },
                { name: 'cream', amount: 150, unit: 'ml' },
                { name: 'butter', amount: 30, unit: 'g' },
                { name: 'onions', amount: 100, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
                { name: 'bread', amount: 100, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'European',
            time: '30 min',
        },
        {
            id: 46,
            name: 'Egg Fried Noodles',
            image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'eggs', amount: 150, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'cabbage', amount: 150, unit: 'g' },
                { name: 'carrots', amount: 100, unit: 'g' },
                { name: 'soy sauce', amount: 30, unit: 'ml' },
                { name: 'vegetable oil', amount: 20, unit: 'ml' },
                { name: 'garlic', amount: 10, unit: 'g' },
            ],
            servings: 3,
            cuisine: 'Chinese',
            time: '20 min',
        },
        {
            id: 47,
            name: 'Cheese and Spinach Stuffed Shells',
            image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'cheese', amount: 250, unit: 'g' },
                { name: 'cream', amount: 100, unit: 'ml' },
                { name: 'eggs', amount: 50, unit: 'g' },
                { name: 'spinach', amount: 200, unit: 'g' },
                { name: 'pasta', amount: 350, unit: 'g' },
                { name: 'tomatoes', amount: 300, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Italian',
            time: '45 min',
        },
        {
            id: 48,
            name: 'Beef Bulgogi',
            image: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'beef', amount: 500, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'soy sauce', amount: 40, unit: 'ml' },
                { name: 'sugar', amount: 20, unit: 'g' },
                { name: 'garlic', amount: 15, unit: 'g' },
                { name: 'ginger', amount: 10, unit: 'g' },
                { name: 'onions', amount: 100, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Korean',
            time: '30 min',
        },
        {
            id: 49,
            name: 'Shrimp Tempura with Rice',
            image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'shrimp', amount: 300, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
                { name: 'eggs', amount: 50, unit: 'g' },
                { name: 'flour', amount: 100, unit: 'g' },
                { name: 'soy sauce', amount: 30, unit: 'ml' },
                { name: 'vegetable oil', amount: 200, unit: 'ml' },
            ],
            servings: 3,
            cuisine: 'Japanese',
            time: '30 min',
        },
        {
            id: 50,
            name: 'Pork Dumplings',
            image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'pork', amount: 300, unit: 'g' },
                { name: 'flour', amount: 250, unit: 'g' },
                { name: 'cabbage', amount: 150, unit: 'g' },
                { name: 'ginger', amount: 10, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
                { name: 'soy sauce', amount: 30, unit: 'ml' },
                { name: 'eggs', amount: 50, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Chinese',
            time: '45 min',
        },
        {
            id: 51,
            name: 'Butter Naan with Dal',
            image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'butter', amount: 60, unit: 'g' },
                { name: 'milk', amount: 100, unit: 'ml' },
                { name: 'eggs', amount: 50, unit: 'g' },
                { name: 'flour', amount: 300, unit: 'g' },
                { name: 'yogurt', amount: 80, unit: 'g' },
                { name: 'onions', amount: 100, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Indian',
            time: '35 min',
        },
        {
            id: 52,
            name: 'Cheesy Baked Potatoes',
            image: 'https://images.pexels.com/photos/34495395/pexels-photo-34495395.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
            ingredients: [
                { name: 'potatoes', amount: 600, unit: 'g' },
                { name: 'cheese', amount: 150, unit: 'g' },
                { name: 'butter', amount: 40, unit: 'g' },
                { name: 'cream', amount: 80, unit: 'ml' },
                { name: 'bacon', amount: 80, unit: 'g' },
                { name: 'broccoli', amount: 100, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'American',
            time: '60 min',
        },
        {
            id: 53,
            name: 'Chicken Chow Mein',
            image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'chicken', amount: 350, unit: 'g' },
                { name: 'cabbage', amount: 150, unit: 'g' },
                { name: 'carrots', amount: 100, unit: 'g' },
                { name: 'peppers', amount: 100, unit: 'g' },
                { name: 'soy sauce', amount: 40, unit: 'ml' },
                { name: 'garlic', amount: 10, unit: 'g' },
                { name: 'vegetable oil', amount: 20, unit: 'ml' },
            ],
            servings: 3,
            cuisine: 'Chinese',
            time: '25 min',
        },
        {
            id: 54,
            name: 'Palak Paneer',
            image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&h=400&fit=crop',
            ingredients: [
                { name: 'cheese', amount: 250, unit: 'g' },
                { name: 'cream', amount: 80, unit: 'ml' },
                { name: 'butter', amount: 30, unit: 'g' },
                { name: 'spinach', amount: 400, unit: 'g' },
                { name: 'onions', amount: 100, unit: 'g' },
                { name: 'garlic', amount: 10, unit: 'g' },
                { name: 'ginger', amount: 10, unit: 'g' },
                { name: 'rice', amount: 300, unit: 'g' },
            ],
            servings: 4,
            cuisine: 'Indian',
            time: '35 min',
        },
    ];

    // Calculate carbon footprint for a recipe
    function calculateRecipeCO2(ingredients) {
        let totalCO2 = 0;
        ingredients.forEach(ing => {
            const name = ing.name.toLowerCase();
            const kgAmount = ing.amount / 1000;
            const co2PerKg = carbonFootprint[name] || 1.0;
            totalCO2 += co2PerKg * kgAmount;
        });
        return Math.round(totalCO2 * 100) / 100;
    }

    // Get carbon rating (A-E scale)
    function getCarbonRating(co2PerServing) {
        if (co2PerServing < 0.5) return { grade: 'A', label: 'Very Low', color: '#2d6a4f' };
        if (co2PerServing < 1.0) return { grade: 'B', label: 'Low', color: '#52b788' };
        if (co2PerServing < 2.0) return { grade: 'C', label: 'Moderate', color: '#f4a261' };
        if (co2PerServing < 4.0) return { grade: 'D', label: 'High', color: '#e76f51' };
        return { grade: 'E', label: 'Very High', color: '#d62828' };
    }

    // Find high-impact ingredients that can be substituted
    function findSubstitutableIngredients(ingredients) {
        const results = [];
        ingredients.forEach(ing => {
            const name = ing.name.toLowerCase();
            if (substitutions[name]) {
                const co2 = (carbonFootprint[name] || 0) * (ing.amount / 1000);
                results.push({
                    ingredient: name,
                    amount: ing.amount,
                    unit: ing.unit,
                    co2: co2,
                    co2PerKg: carbonFootprint[name] || 0,
                    alternatives: substitutions[name],
                });
            }
        });
        // Sort by carbon impact (highest first)
        results.sort((a, b) => b.co2 - a.co2);
        return results;
    }

    // Calculate carbon savings from a substitution
    function calculateSavings(originalIngredient, replacementName, amountKg) {
        const originalCO2 = (carbonFootprint[originalIngredient] || 1.0) * amountKg;
        const replacementCO2 = (carbonFootprint[replacementName] || 1.0) * amountKg;
        const savings = originalCO2 - replacementCO2;
        const percentage = Math.round((savings / originalCO2) * 100);
        return {
            originalCO2: Math.round(originalCO2 * 100) / 100,
            replacementCO2: Math.round(replacementCO2 * 100) / 100,
            savingsKg: Math.round(savings * 100) / 100,
            savingsPercent: percentage,
        };
    }

    // Get fun equivalence for CO2 savings
    function getCO2Equivalence(savingsKg) {
        // Average car emits ~0.21 kg CO2 per km
        const kmDriving = Math.round(savingsKg / 0.21 * 10) / 10;
        // Average tree absorbs ~22 kg CO2 per year = ~0.06 kg per day
        const treeDays = Math.round(savingsKg / 0.06 * 10) / 10;
        // Average phone charge = ~0.005 kg CO2
        const phoneCharges = Math.round(savingsKg / 0.005);

        const equivalences = [];
        if (kmDriving >= 0.1) equivalences.push(`${kmDriving} km of driving`);
        if (treeDays >= 0.1) equivalences.push(`what a tree absorbs in ${treeDays} days`);
        if (phoneCharges >= 1) equivalences.push(`${phoneCharges} phone charges`);
        return equivalences;
    }

    // Find ingredients not present in carbonFootprint database
    function findUnknownIngredients(ingredients) {
        return ingredients.filter(ing => !(ing.name.toLowerCase() in carbonFootprint));
    }

    // Dynamically add ingredient data fetched from AI
    function addIngredientData(name, data) {
        const key = name.toLowerCase();
        if (data.co2PerKg != null) carbonFootprint[key] = data.co2PerKg;
        if (data.nutrition) nutritionData[key] = data.nutrition;
        if (data.healthBenefits) healthBenefits[key] = data.healthBenefits;
        if (data.substitutions && data.substitutions.length > 0) substitutions[key] = data.substitutions;
    }

    return {
        carbonFootprint,
        nutritionData,
        substitutions,
        healthBenefits,
        sampleRecipes,
        calculateRecipeCO2,
        getCarbonRating,
        findSubstitutableIngredients,
        calculateSavings,
        getCO2Equivalence,
        findUnknownIngredients,
        addIngredientData,
    };
})();
